### ISSUE TITLE
i cant download the file as mp3

### ISSUE THREAD

**Issue by reav85** [Rudloff/alltube#169]
# New issue
## Your environment

Please answer these questions when reporting a new issue:

**What is your operating system (Windows, Linux, OSX, etc.)?**
Linux
**What is your web server (Apache, IIS, etc.)?**
Apache2
**What version of AllTube are you using?**
current
**How did you install AllTube (with Git or with a release package)?**
composer
**What version of PHP are you using?**
7.2.3
**What version of Python are you using?**
2.7
**What version of youtube-dl are you using?**
latest
**Do you get any PHP-related errors in your webserver's logs?**
no
**What is the content of your `config/config.yml` file?**
```yaml
# Path to your youtube-dl binary
youtubedl: vendor/rg3/youtube-dl/youtube_dl/__main__.py

# Path to your python binary
python: /usr/bin/python

# An array of parameters to pass to youtube-dl
params:
    - --no-warnings
    - --ignore-errors
    - --flat-playlist
    - --restrict-filenames

# True to enable audio conversion
convert: true
avconv: /usr/bin/

# True to enable advanced conversion mode
convertAdvanced: true

# List of formats available in advanced conversion mode
convertAdvancedFormats: [mp3, avi]

# Path to your avconv or ffmpeg binary


# avconv/ffmpeg logging level.
avconvVerbosity: error

# Path to the directory that contains the phantomjs binary.
phantomjsDir: /usr/local/bin/

# True to disable URL rewriting
uglyUrls: true

# True to stream videos through server
stream: true

# MP3 bitrate when converting (in kbit/s)
audioBitrate: 128
```

**Please provide the URL of a video that causes the issue.**

## Describe your issue
it work everything except the mp3 conversion i can download the video file as mp4 or web or 3gp even if i did convertAdvancedFormats: [mp3, avi]
