### ISSUE TITLE
Can't find avconv or ffmpeg at vendor/bin/ffmpeg

### ISSUE THREAD

**Issue by louanbastos** [Rudloff/alltube#210]
Hi, I download Alltube from a release package (https://github.com/Rudloff/alltube/releases) when i try to download remux the download failed and when i try to convert to mp3 i got this error(Can't find avconv or ffmpeg at vendor/avconv.), I use cPanel, how i just extract and edit a config to change only name, how can i make it work? thanks anyway

Btw, have a new version of youtube-dl and ffmpeg

**Comment by Rudloff** [comment]
Hello,
(Please don't remove the issue template.)

The release package does not contain ffmpeg, so you need to install either ffmpeg or avconv and edit your `config/config.yml` file as explained [here](https://github.com/Rudloff/alltube/blob/master/resources/FAQ.md#enable-audio-conversion) so Alltube can know where this binary is:
```yaml
avconv: path/to/ffmpeg
```

**Comment by louanbastos** [comment]
> Hello,
> (Please don't remove the issue template.)
> 
> The release package does not contain ffmpeg, so you need to install either ffmpeg or avconv and edit your `config/config.yml` file as explained [here](https://github.com/Rudloff/alltube/blob/master/resources/FAQ.md#enable-audio-conversion) so Alltube can know where this binary is:
> 
> ```yaml
> avconv: path/to/ffmpeg
> ```

thanks for answer fast, but i have windows and i put on my server hosting dl.ggbr.me - i try to make work, how can i download ffmpeg or libav do work propely, please i newbie on this :D thanks again

how or where can i download binaries?

**Comment by Rudloff** [comment]
What OS is your server using? ffmpeg should be available in the OS package manager.
Alternatively, if your server uses Linux, an easy way to download ffmpeg is [these prebuilt binaries](https://www.johnvansickle.com/ffmpeg/).

**Comment by louanbastos** [comment]
> What OS is your server using? ffmpeg should be available in the OS package manager.
> Alternatively, if your server uses Linux, an easy way to download ffmpeg is [these prebuilt binaries](https://www.johnvansickle.com/ffmpeg/).

i think is CentOS i'll try it, anyway thanks, i'll reply here after check. :D

**Comment by louanbastos** [comment]
> What OS is your server using? ffmpeg should be available in the OS package manager.
> Alternatively, if your server uses Linux, an easy way to download ffmpeg is [these prebuilt binaries](https://www.johnvansickle.com/ffmpeg/).


This is my server config:
https://i.imgur.com/7vDbseh.png
What is the prebuild i use?

**Comment by Rudloff** [comment]
Your server has an amd64 processor so you need to use this one: https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz

**Comment by louanbastos** [comment]
> Your server has an amd64 processor so you need to use this one: https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz

I dowloaded and put on my server, but still don't work
What i'm doing wrong?

my config.yml
```yml
---
# Path to your youtube-dl binary
youtubedl: vendor/rg3/youtube-dl/youtube_dl/__main__.py

# Path to your python binary
python: /usr/bin/python

avconv: vendor/ffmpeg

ffmpeg: vendor/ffmpeg

# An array of parameters to pass to youtube-dl
params:
    - --no-warnings
    - --ignore-errors
    - --flat-playlist
    - --restrict-filenames
    - --no-playlist

# True to enable audio conversion
convert: true

# True to enable advanced conversion mode
convertAdvanced: false

# List of formats available in advanced conversion mode
convertAdvancedFormats: [mp3, avi, flv, wav]

# Path to your avconv or ffmpeg binary
avconv: vendor/bin/ffmpeg

# avconv/ffmpeg logging level.
avconvVerbosity: error

# Path to the directory that contains the phantomjs binary.
phantomjsDir: vendor/bin/

# True to disable URL rewriting
uglyUrls: false

# True to stream videos through server
stream: false

# True to enable remux mode (merge best audio and best video)
remux: true

# MP3 bitrate when converting (in kbit/s)
audioBitrate: 320

# App name
appName: GGDownload

```
