### ISSUE TITLE
Different video format gotten from website and as library.

### ISSUE THREAD

**Issue by kinglyl** [Rudloff/alltube#260]
# Different video format gotten from website and as library.

## Your environment
Please answer these questions when reporting a new issue:

**What is your operating system (Windows, Linux, OSX, etc.)?**
`Ubuntu 18.04 LTS`
**What is your web server (Apache, IIS, etc.)?**
`Apache2`
**What version of AllTube are you using?**
`LTS by 2020-02-12`
**How did you install AllTube (with Git or with a release package)?**
`Git`
**What version of PHP are you using?**
`7.2.24`
**What version of Python are you using?**
`3.6.9`
**What version of youtube-dl are you using?**
`2020.01.01`
**Do you get any PHP-related errors in your webserver's logs?**
*no*
**What is the content of your `config/config.yml` file?**
```yml
---
# Path to your youtube-dl binary
youtubedl: vendor/rg3/youtube-dl/youtube_dl/__main__.py

# Path to your python binary
python: /usr/bin/python3

# An array of parameters to pass to youtube-dl
params:
    - --no-warnings
    - --ignore-errors
    - --flat-playlist
    - --restrict-filenames
    - --no-playlist

# True to enable audio conversion
convert: true

# True to enable advanced conversion mode
convertAdvanced: true

# List of formats available in advanced conversion mode
convertAdvancedFormats: [mp3, avi, flv, wav]

# Path to your avconv or ffmpeg binary
avconv: vendor/bin/ffmpeg

# avconv/ffmpeg logging level.
avconvVerbosity: error

# Path to the directory that contains the phantomjs binary.
phantomjsDir: vendor/bin/

# True to disable URL rewriting
uglyUrls: false

# True to stream videos through server
stream: true

# True to enable remux mode (merge best audio and best video)
remux: true

# MP3 bitrate when converting (in kbit/s)
audioBitrate: 128

# App name
appName: AllTube Download

# Generic formats supported by youtube-dl
genericFormats:
    best: Best
    bestvideo+bestaudio: Remux best video with best audio
    worst: Worst
```

## Describe your issue
I use Alltube as a libaray to get pornhub videos .
But recently I found that when I get a pornhub video by website(Alltube website I bulit),I can get a 'mp4' file, but I can only get 'm3u8' file while using it as a function.

my Alltube website:
https://52proxy.fun/ytb/
