### ISSUE TITLE
Cannot download video from any source

### ISSUE THREAD

**Issue by shahishasank** [Rudloff/alltube#287]
# Cannot download video from any source

## Your environment

Please answer these questions when reporting a new issue:

**What is your operating system (Windows, Linux, OSX, etc.)?**
Windows 8.1 x64

**What is your web server (Apache, IIS, etc.)?**
Xampp Apache

**What version of AllTube are you using?**
2.3.0

**How did you install AllTube (with Git or with a release package)?**
Release package

**What version of PHP are you using?**
7.3.0

**What version of Python are you using?**
3.8.3

**What version of youtube-dl are you using?**
Whatever AllTube 2.3.0 uses

**Do you get any PHP-related errors in your webserver's logs?**
No error in error.log file

**What is the content of your `config/config.yml` file?**

```yaml
---
# Path to your youtube-dl binary
youtubedl: vendor/ytdl-org/youtube-dl/youtube_dl/__main__.py

# Path to your python binary
python: /usr/bin/python

# An array of parameters to pass to youtube-dl
params:
    - --no-warnings
    - --ignore-errors
    - --flat-playlist
    - --restrict-filenames
    - --no-playlist

# True to enable audio conversion
convert: false

# True to enable advanced conversion mode
convertAdvanced: false

# List of formats available in advanced conversion mode
convertAdvancedFormats: [mp3, avi, flv, wav]

# Path to your avconv or ffmpeg binary
avconv: vendor/bin/ffmpeg

# avconv/ffmpeg logging level.
avconvVerbosity: error

# Path to the directory that contains the phantomjs binary.
phantomjsDir: vendor/bin/

# True to disable URL rewriting
uglyUrls: false

# True to stream videos through server
# Set to "ask" if you want to allow it but not enable by default.
stream: false

# True to enable remux mode (merge best audio and best video)
remux: false

# MP3 bitrate when converting (in kbit/s)
audioBitrate: 128

# App name
appName: AllTube Download

# Generic formats supported by youtube-dl
genericFormats:
    best: Best
    bestvideo+bestaudio: Remux best video with best audio
    worst: Worst

# Enable debug mode.
debug: false

```

**Please provide the URL of a video that causes the issue.**
I tried multiple links from youtube and dailymotion, none worked. For ex
https://www.youtube.com/watch?v=DUBkmULoBhA
https://www.youtube.com/watch?v=arj7oStGLkU

## Describe your issue
Here is the SS of the page when I click on download
![image](https://user-images.githubusercontent.com/32937688/83961365-f0263380-a8af-11ea-8156-ec6d0942c15f.png)
I tried different links fro youtube and dailymotion, same error everytime. Please suggest if I'm doing something wrong.
