### ISSUE TITLE
Audio Only Option Not Working.

### ISSUE THREAD

**Issue by varunsridharan** [Rudloff/alltube#296]
# New issue

## Your environment

Please answer these questions when reporting a new issue:

**What is your operating system (Windows, Linux, OSX, etc.)?**
Windows

**What is your web server (Apache, IIS, etc.)?**
Apache

**What version of AllTube are you using?**
2.3.0

**How did you install AllTube (with Git or with a release package)?**
Git

**What version of PHP are you using?**
7.3

**What version of Python are you using?**
3.6.4

**What version of youtube-dl are you using?**
installed using composer so it should be latest

**Do you get any PHP-related errors in your webserver's logs?**
Nope

**What is the content of your `config/config.yml` file?**

```yaml
---
# Path to your youtube-dl binary
youtubedl: vendor/ytdl-org/youtube-dl/youtube_dl/__main__.py

# Path to your python binary
python: C:\Program Files\Python36\python.exe

# An array of parameters to pass to youtube-dl
params:
    - --no-warnings
    - --ignore-errors
    - --flat-playlist
    - --restrict-filenames
    - --no-playlist

# True to enable audio conversion
convert: true

# True to enable advanced conversion mode
convertAdvanced: true

# List of formats available in advanced conversion mode
convertAdvancedFormats: [mp3, avi, flv, wav]

# Path to your ffmpeg binary
ffmpeg: E:\localhost\etc\apps\youtube-dl\ffmpeg\bin\ffmpeg.exe

avconv: E:\localhost\etc\apps\youtube-dl\ffmpeg\bin\ffmpeg.exe

# ffmpeg logging level.
ffmpegVerbosity: error

# Path to the directory that contains the phantomjs binary.
phantomjsDir: E:\localhost\etc\apps\youtube-dl\phantomjs.exe

# True to disable URL rewriting
uglyUrls: false

# True to stream videos through server
# Set to "ask" if you want to allow it but not enable by default.
stream: false

# True to enable remux mode (merge best audio and best video)
remux: false

# MP3 bitrate when converting (in kbit/s)
audioBitrate: 128

# App name
appName: YouTube DL

# Generic formats supported by youtube-dl
genericFormats:
    best/bestvideo: Best
    bestvideo+bestaudio: Remux best video with best audio
    worst/worstvideo: Worst
    bestaudio: Best audio

# Enable debug mode.
debug: false

```

**Please provide the URL of a video that causes the issue.**
https://www.youtube.com/watch?v=REjFtvBTPMc

## Describe your issue
I some how got audio only option enabled. but its actually not working.
when i click download when using audio only option the file size is too low around (400KB)

![https://s2.do-spaces.com/2020/Jul/12/1594569108-15.jpg](https://s2.do-spaces.com/2020/Jul/12/1594569108-15.jpg)
