### ISSUE TITLE
Downlaod locally isn't working

### ISSUE THREAD

**Issue by tomcdj71** [Rudloff/alltube#303]
# New issue

## Your environment

Please answer these questions when reporting a new issue:

**What is your operating system (Windows, Linux, OSX, etc.)?** Ubuntu 18.4 

**What is your web server (Apache, IIS, etc.)?** Nginx

**What version of AllTube are you using?** 3.0.0-beta

**How did you install AllTube (with Git or with a release package)?** Release package

**What version of PHP are you using?** 7.4

**What version of Python are you using?** 3.8

**What version of youtube-dl are you using?** 2018.03.14 (?)

**Do you get any PHP-related errors in your webserver's logs?** Yes

**What is the content of your `config/config.yml` file?**

```yaml
# Path to your youtube-dl binary
youtubedl: vendor/ytdl-org/youtube-dl/youtube_dl/__main__.py
#youtubedl: /usr/bin/youtube-dl

# Path to your python binary
python: /usr/bin/python3

# An array of parameters to pass to youtube-dl
params:
    - --no-warnings
    - --ignore-errors
    - --flat-playlist
    - --restrict-filenames
    - --no-playlist

# True to enable audio conversion
convert: false

# True to enable advanced conversion mode
convertAdvanced: true

# List of formats available in advanced conversion mode
convertAdvancedFormats: [mp3, avi, flv, wav]

# Path to your ffmpeg binary
ffmpeg: /usr/bin/ffmpeg

# ffmpeg logging level.
ffmpegVerbosity: error

# Path to the directory that contains the phantomjs binary.
phantomjsDir: /usr/bin/phantomjs

# True to disable URL rewriting
uglyUrls: false

# True to stream videos through server
# Set to "ask" if you want to allow it but not enable by default.
stream: ask

# True to enable remux mode (merge best audio and best video)
remux: false

# MP3 bitrate when converting (in kbit/s)
audioBitrate: 320

# App name
appName: AllTube Download

# Generic formats supported by youtube-dl
genericFormats:
    best/bestvideo: Best
    bestvideo+bestaudio: Remux best video with best audio
    worst/worstvideo: Worst

# Enable debug mode.
debug: true
```

**Please provide the URL of a video that causes the issue.**

## Describe your issue
Hi, I have installed AllTube on a server but it seems I can't download videos/audio directly on the server.
I'm able to download to my PC, but not to my server.

For example, it produce these errors :
```L’encodage de caractères d’un document en texte brut n’a pas été déclaré. Le document sera affiché avec des caractères incorrects pour certaines configurations de navigateur si le document contient des caractères en dehors de la plage US-ASCII. L’encodage de caractères du fichier doit être déclaré dans le protocole de transfert ou le fichier doit utiliser une marque d’ordre des octets (BOM) comme signature d’encodage```
Or also this 403 : 
```
https://r5---sn-4g5ednss.googlevideo.com/videoplayback?expire=1598454149&ei=JSVGX8qgBpTm1gKGrZ6ABw&ip=5.9.145.252&id=o-ACJqZHbdQy2FUMTWZw9C75u0L3NJF3_blNbwqQDqkW2R&itag=18&source=youtube&requiressl=yes&mh=th&mm=31,26&mn=sn-4g5ednss,sn-f5f7lnl7&ms=au,onr&mv=m&mvi=5&pl=21&gcr=ua&initcwndbps=920000&vprv=1&mime=video/mp4&gir=yes&clen=13045785&ratebypass=yes&dur=191.053&lmt=1575728917957721&mt=1598432436&fvip=5&c=WEB&txp=5431432&sparams=expire,ei,ip,id,itag,source,requiressl,gcr,vprv,mime,gir,clen,ratebypass,dur,lmt&lsparams=mh,mm,mn,ms,mv,mvi,pl,initcwndbps&lsig=AG3C_xAwRAIgIwDShx5iP27-7Y6JDR-ypbUslskAIXHotcG8cNBLpfoCIGp9RZ9OQ1YxOYYPVCP62fvL6gOV2bMfUPHnxTP-KZlh&sig=AOq0QJ8wRgIhAIqb1o-xFtVSaStGzR4j2mPa8eeokoh59Lapjbyv5mEcAiEA-L6IrQ57_8iIu5L8O0lFshpdmrf5S8o0lrbedp1z4Vc=
```

Describing this error showed me that I'm on an old youtube-dl version (installed via apt), but except that, I don't understand why it doesn't want to download on the server. 
I've tried to add the parameter `--output /my/path/%(title)s.%(ext)s` But that was a no-go too...
