### ISSUE TITLE
Unable to download videos that alltube's main site is able to download

### ISSUE THREAD

**Issue by EthanJohnson** [Rudloff/alltube#322]
# New issue

## Your environment

Please answer these questions when reporting a new issue:

**What is your operating system (Windows, Linux, OSX, etc.)?**
Ubuntu 18.04 LTS

**What is your web server (Apache, IIS, etc.)?** 
Whatever the cloudron install uses (DigitalOcean premade image)
**What version of AllTube are you using?** 
2.3.0
**How did you install AllTube (with Git or with a release package)?**
Cloudron
**What version of PHP are you using?**
Whatever the cloudron package uses
**What version of Python are you using?**
Whatever the cloudron package uses
**What version of youtube-dl are you using?**
Whatever the cloudron package uses
**Do you get any PHP-related errors in your webserver's logs?**
Not sure if from php, but these are the logs when I run AllTube from Cloudron with the below URL:
[https://pastebin.com/uy40v7pj](https://pastebin.com/uy40v7pj)
**What is the content of your `config/config.yml` file?**

```yaml
# Path to your youtube-dl binary
youtubedl: vendor/ytdl-org/youtube-dl/youtube_dl/__main__.py

# Path to your python binary
python: /usr/bin/python

# An array of parameters to pass to youtube-dl
params:
    - --no-warnings
    - --ignore-errors
    - --flat-playlist
    - --restrict-filenames
    - --no-playlist

# True to enable audio conversion
convert: true

# True to enable advanced conversion mode
convertAdvanced: true

# List of formats available in advanced conversion mode
convertAdvancedFormats: [mp3, avi, flv, wav]

# Path to your avconv or ffmpeg binary
avconv: /usr/bin/ffmpeg

# avconv/ffmpeg logging level.
avconvVerbosity: error

# Path to the directory that contains the phantomjs binary.
phantomjsDir: vendor/bin/

# True to disable URL rewriting
uglyUrls: false

# True to stream videos through server
# Set to "ask" if you want to allow it but not enable by default.
stream: true

# True to enable remux mode (merge best audio and best video)
remux: true

# MP3 bitrate when converting (in kbit/s)
audioBitrate: 256

# App name
appName: Cloudron Alltube Download

# Generic formats supported by youtube-dl
genericFormats:
    best: Best
    bestvideo+bestaudio: Remux best video with best audio
    worst: Worst

# Enable debug mode.
debug: false
```

**Please provide the URL of a video that causes the issue.**
https://www.reddit.com/r/AmongUs/comments/jihmjo/when_youre_imposter_and_the_dead_body_is_kinda_sus/
## Describe your issue
https://alltubedownload.net/ is able to download the above link fine. But when I put the exact same link into my Cloudron hosted version, it shows [this error](https://i.imgur.com/nu8SQO2.png).
