### ISSUE TITLE
"Best quality" option is not the actual video best quality

### ISSUE THREAD

**Issue by stemy2** [Rudloff/alltube#324]
# New issue

## Your environment

Please answer these questions when reporting a new issue:

**What is your operating system (Windows, Linux, OSX, etc.)?**
Linux
**What is your web server (Apache, IIS, etc.)?**
NGINX
**What version of AllTube are you using?**
2.3.0
**How did you install AllTube (with Git or with a release package)?**
Yunohost package
**What version of PHP are you using?**
7.3
**What version of Python are you using?**
2.7.16
**What version of youtube-dl are you using?**
Don't know
**Do you get any PHP-related errors in your webserver's logs?**
No
**What is the content of your `config/config.yml` file?**

```yaml
---
# Path to your youtube-dl binary
youtubedl: vendor/ytdl-org/youtube-dl/youtube_dl/__main__.py

# Path to your python binary
python: /usr/bin/python

# An array of parameters to pass to youtube-dl
params:
    - --no-warnings
    - --ignore-errors
    - --flat-playlist
    - --restrict-filenames
    - --no-playlist

# True to enable audio conversion
convert: true

# True to enable advanced conversion mode
convertAdvanced: true

# List of formats available in advanced conversion mode
convertAdvancedFormats: [mp3, avi, flv, wav]

# Path to your avconv or ffmpeg binary
avconv: /usr/bin/ffmpeg

# avconv/ffmpeg logging level.
avconvVerbosity: error

# Path to the directory that contains the phantomjs binary.
phantomjsDir: vendor/bin/

# True to disable URL rewriting
uglyUrls: false

# True to stream videos through server
stream: true

# True to enable remux mode (merge best audio and best video)
remux: true

# MP3 bitrate when converting (in kbit/s)
audioBitrate: 128

# App name
appName: AllTube Download

```

**Please provide the URL of a video that causes the issue.**
https://youtu.be/a-bvPLbeRHE
## Describe your issue
When i select "best quality", instead of the expected 1080p quality (the actual resolution of the video), the output resolution is 640*272.
