### ISSUE TITLE
Error when trying to download https://www.youtube.com/watch?v=dzgEjZyN9ec

### ISSUE THREAD

**Issue by jdaviescoates** [Rudloff/alltube#350]
# New issue

## Your environment

Please answer these questions when reporting a new issue:

**What is your operating system (Windows, Linux, OSX, etc.)?**

Ubuntu 18.04

**What is your web server (Apache, IIS, etc.)?**

Apache, I think.

**What version of AllTube are you using?**

The Cloudron package

**How did you install AllTube (with Git or with a release package)?**

Using Cloudron

**What version of PHP are you using?**

Not sure.

**What version of Python are you using?**

Not sure.

**What version of youtube-dl are you using?**

Not sure.

**Do you get any PHP-related errors in your webserver's logs?**

**What is the content of your `config/config.yml` file?**

```yaml
# Path to your youtube-dl binary
youtubedl: /usr/local/bin/youtube-dl

# Path to your python binary
python: /usr/bin/python

# An array of parameters to pass to youtube-dl
params:
    - --no-warnings
    - --ignore-errors
    - --flat-playlist
    - --restrict-filenames
    - --no-playlist

# True to enable audio conversion
convert: true

# True to enable advanced conversion mode
convertAdvanced: true

# List of formats available in advanced conversion mode
convertAdvancedFormats: [mp3, avi, flv, wav]

# Path to your avconv or ffmpeg binary
avconv: /usr/bin/ffmpeg

# avconv/ffmpeg logging level.
avconvVerbosity: error

# Path to the directory that contains the phantomjs binary.
phantomjsDir: vendor/bin/

# True to disable URL rewriting
uglyUrls: false

# True to stream videos through server
# Set to "ask" if you want to allow it but not enable by default.
stream: true

# True to enable remux mode (merge best audio and best video)
remux: true

# MP3 bitrate when converting (in kbit/s)
audioBitrate: 256

# App name
appName: Cloudron Alltube Download

# Generic formats supported by youtube-dl
genericFormats:
    best: Best
    bestvideo+bestaudio: Remux best video with best audio
    worst: Worst

# Enable debug mode.
debug: false
```

**Please provide the URL of a video that causes the issue.**

https://www.youtube.com/watch?v=dzgEjZyN9ec

## Describe your issue

Whenever I try to download this video I get this error:

'/usr/bin/python' '/usr/local/bin/youtube-dl' '--no-warnings' '--ignore-errors' '--flat-playlist' '--restrict-filenames' '--no-playlist' '--dump-single-json' 'https://www.youtube.com/watch?v=dzgEjZyN9ec' '-f' 'bestaudio/best/bestvideo' failed with this error:
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
