### ISSUE TITLE
Why i18n is broken ?

### ISSUE THREAD

**Issue by volfclub** [Rudloff/alltube#359]
# New issue

## Your environment

Please answer these questions when reporting a new issue:

**What is your operating system (Windows, Linux, OSX, etc.)?**
centos7
**What is your web server (Apache, IIS, etc.)?**
nginx
**What version of AllTube are you using?**
v3
**How did you install AllTube (with Git or with a release package)?**
release package
**What version of PHP are you using?**
7.4
**What version of Python are you using?**

**What version of youtube-dl are you using?**

**Do you get any PHP-related errors in your webserver's logs?**

**What is the content of your `config/config.yml` file?**

```yaml
---
# Path to your youtube-dl binary
youtubedl: vendor/ytdl-org/youtube-dl/youtube_dl/__main__.py

# Path to your python binary
python: /usr/bin/python

# An array of parameters to pass to youtube-dl
params:
    - --no-warnings
    - --ignore-errors
    - --flat-playlist
    - --restrict-filenames
    - --no-playlist

# True to enable audio conversion
convert: true

# True to enable advanced conversion mode
convertAdvanced: false

# List of formats available in advanced conversion mode
convertAdvancedFormats: [mp3, avi, flv, wav]

# Path to your ffmpeg binary
ffmpeg: /usr/bin/ffmpeg

# ffmpeg logging level.
ffmpegVerbosity: error

# Path to the directory that contains the phantomjs binary.
phantomjsDir: /usr/bin/

# True to disable URL rewriting
uglyUrls: true

# True to stream videos through server
# Set to "ask" if you want to allow it but not enable by default.
stream: ask

# True to enable remux mode (merge best audio and best video)
remux: true

# MP3 bitrate when converting (in kbit/s)
audioBitrate: 128

# App name
appName: AllTube Download

# Generic formats supported by youtube-dl
genericFormats:
    best/bestvideo: Best
    bestvideo+bestaudio: Remux best video with best audio
    worst/worstvideo: Worst

# Enable debug mode.
debug: false

# True to enable audio conversion mode by default
defaultAudio: false

# False to disable convert seek functionality
convertSeek: true
```

**Please provide the URL of a video that causes the issue.**

## Describe your issue

![图片](https://user-images.githubusercontent.com/47265026/120930842-9efa8b00-c721-11eb-9a7b-c44309b6b3e6.png)

There are two text languages ​​on the webpage at the same time, and I don't have any idea about it.
