### ISSUE TITLE
Config option "convert: false" doesn't work

### ISSUE THREAD

**Issue by v-bulynkin** [Rudloff/alltube#373]
## Your environment

**What version of AllTube are you using?**
Latest docker image - rudloff/alltube.

**What is the content of your `config/config.yml` file?**

```yaml
appName: AWESOME
convert: false
convertAdvanced: false
stream: false
remux: false
```
## Describe your issue
I simply use docker with copying a config file into the latest **rudloff/alltube** docker image. The **appName** option is working (which points out that the config file is in place), but **convert** is not. Why? I would like to remove the MP3 tab from the Alltube's frontpage.
