### ISSUE TITLE
"Remux best video with best audio" will cause web server 503 if I try to download another video.

### ISSUE THREAD

**Issue by nxtreaming** [Rudloff/alltube#376]
# New issue

## Your environment
ubuntu 20.04 LTS

Please answer these questions when reporting a new issue:

**What is your operating system (Windows, Linux, OSX, etc.)?**
Ubuntu 20.04.03 LTS

**What is your web server (Apache, IIS, etc.)?**
nginx

**What version of AllTube are you using?**

the master branch

**How did you install AllTube (with Git or with a release package)?**

git.

**What version of PHP are you using?**

PHP 7.4.25 (cli) (built: Nov  4 2021 04:41:34) ( ZTS )

**What version of Python are you using?**

Python 3.8.10

**What version of youtube-dl are you using?**

I use "yt-dlp-2021.12.01"

**Do you get any PHP-related errors in your webserver's logs?**

NO

**What is the content of your `config/config.yml` file?**

```yaml

# Path to your youtube-dl binary
#youtubedl: vendor/ytdl-org/youtube-dl/youtube_dl/__main__.py
youtubedl: vendor/yt-dlp/yt-dlp-2021.12.01/yt_dlp/__main__.py

# Path to your python binary
python: /usr/bin/python

# An array of parameters to pass to youtube-dl
params:
    - --no-warnings
    - --ignore-errors
    - --flat-playlist
    - --restrict-filenames
    - --no-playlist

# True to enable audio conversion
convert: false

# True to enable advanced conversion mode
convertAdvanced: false

# List of formats available in advanced conversion mode
convertAdvancedFormats: [mp3, avi, flv, wav]

# Path to your ffmpeg binary
ffmpeg: /usr/local/bin/ffmpeg

# ffmpeg logging level.
ffmpegVerbosity: error

# Path to the directory that contains the phantomjs binary.
phantomjsDir: /usr/bin/

# True to disable URL rewriting
uglyUrls: false

# True to stream videos through server
# Set to "ask" if you want to allow it but not enable by default.
stream: false

# True to enable remux mode (merge best audio and best video)
remux: true

# MP3 bitrate when converting (in kbit/s)
audioBitrate: 128

# App name
appName: AllTube Download

# Generic formats supported by youtube-dl
genericFormats:
    bestvideo+bestaudio: Remux best video with best audio
    best/bestvideo: Best
    #worst/worstvideo: Worst

# Enable debug mode.
debug: false

# True to enable audio conversion mode by default
defaultAudio: false

# False to disable convert seek functionality
convertSeek: true
```

**Please provide the URL of a video that causes the issue.**

## Describe your issue

I can only download another video after the first video has been finished in "Remux best video with best audio" option

Thanks.
