### ISSUE TITLE
Manifest.json start URL is wrong, making a 404 error when saving a shortcut in Android

### ISSUE THREAD

**Issue by LoganTann** [Rudloff/alltube#384]
# New issue

## Your environment

Please answer these questions when reporting a new issue:

**What is your operating system (Windows, Linux, OSX, etc.)?**
> Android

**What is your web server (Apache, IIS, etc.)?**
> Apache

**What version of AllTube are you using?**
> commit fb78ecb 

**How did you install AllTube (with Git or with a release package)?**
> via git clone + composer install

**What version of PHP are you using?**
> 8.0

**What version of Python are you using?**
> either 2.7.18, or 3.8.10

**What version of youtube-dl are you using?**
> the one that was shipped with composer

**Do you get any PHP-related errors in your webserver's logs?**
> 404, but it's due to what causes the Issue

<details><summary><b>What is the content of your `config/config.yml` file?</b></summary>

```yaml
---
# Path to your youtube-dl binary
youtubedl: vendor/ytdl-org/youtube-dl/youtube_dl/__main__.py

# Path to your python binary
python: /usr/bin/python

# An array of parameters to pass to youtube-dl
params:
    - --no-warnings
    - --ignore-errors
    - --flat-playlist
    - --restrict-filenames
    - --no-playlist

# True to enable audio conversion
convert: true

# True to enable advanced conversion mode
convertAdvanced: true

# List of formats available in advanced conversion mode
convertAdvancedFormats: [mp3, avi, flv, wav]

# Path to your ffmpeg binary
ffmpeg: /usr/bin/ffmpeg

# ffmpeg logging level.
ffmpegVerbosity: error

# Path to the directory that contains the phantomjs binary.
phantomjsDir: /usr/bin/

# True to disable URL rewriting
uglyUrls: false

# True to stream videos through server
# Set to "ask" if you want to allow it but not enable by default.
stream: false

# True to enable remux mode (merge best audio and best video)
remux: false

# MP3 bitrate when converting (in kbit/s)
audioBitrate: 128

# App name
appName: AllTube Download

# Generic formats supported by youtube-dl
genericFormats:
    best/bestvideo: Best
    bestvideo+bestaudio: Remux best video with best audio
    worst/worstvideo: Worst

# Enable debug mode.
debug: false

# True to enable audio conversion mode by default
defaultAudio: false

# False to disable convert seek functionality
convertSeek: true
```

</details>

**Please provide the URL of a video that causes the issue.**
> \<none\>

## Describe your issue

1. Go to alltube using chrome for android
2. Tap the menu icon (3 dots in upper right-hand corner) and tap "Add to homescreen".
3. You’ll be able to enter a name for the shortcut, and then Chrome will add it to your home screen.
4. **When clicking the shortcut, it opens to `<alltube URL>/resources` instead of `<alltube URL>/`**

This might be due to the manifest.json, which is located in the resources folder, but the `start_url` property is defined as `./` instead of `../`

Note to @Rudloff : I see some duplicate/spam issues in this repo. If you need help, I can help to moderate the tickets.
