### ISSUE TITLE
Many sources not supported are there any way that we can update the yt-dl?

### ISSUE THREAD

**Issue by anthonyinit** [Rudloff/alltube#395]
# New issue

## Your environment

Please answer these questions when reporting a new issue:

**What is your operating system (Windows, Linux, OSX, etc.)?*Debian 10*

**What is your web server (Apache, IIS, etc.)?*Nginx*

**What version of AllTube are you using?*Lates what i can download here*

**How did you install AllTube (with Git or with a release package)?*Directly to my server after downloading the zip*

**What version of PHP are you using?*7.4*

**What version of Python are you using?*Python 2.7.16*

**What version of youtube-dl are you using?*Not sure how to check I'm just using the file i downloaded from here*

**Do you get any PHP-related errors in your webserver's logs?*/usr/bin/python' 'vendor/ytdl-org/youtube-dl/youtube_dl/__main__.py' '--no-warnings' '--ignore-errors' '--flat-playlist' '--restrict-filenames' '--no-playlist' '--dump-single-json' 'https://www.xvideos.com/video61039269/24151053/0/hungover_fuck_for_samantha_flair' '-f' 'best[protocol=https]/best[protocol=http]/bestvideo[protocol=https]/bestvideo[protocol=http]' failed with this error:
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.*

**What is the content of your `config/config.yml` file?**
```yaml
---
# Path to your youtube-dl binary
youtubedl: vendor/ytdl-org/youtube-dl/youtube_dl/__main__.py

# Path to your python binary
python: /usr/bin/python

# An array of parameters to pass to youtube-dl
params:
    - --no-warnings
    - --ignore-errors
    - --flat-playlist
    - --restrict-filenames
    - --no-playlist

# True to enable audio conversion
convert: true

# True to enable advanced conversion mode
convertAdvanced: true

# List of formats available in advanced conversion mode
convertAdvancedFormats: [mp3, avi, flv, wav]

# Path to your ffmpeg binary
ffmpeg: /usr/bin/ffmpeg

# ffmpeg logging level.
ffmpegVerbosity: error

# Path to the directory that contains the phantomjs binary.
phantomjsDir: /usr/bin/

# True to disable URL rewriting
uglyUrls: false

# True to stream videos through server
# Set to "ask" if you want to allow it but not enable by default.
stream: true

# True to enable remux mode (merge best audio and best video)
remux: true

# MP3 bitrate when converting (in kbit/s)
audioBitrate: 128

# App name
appName: all Tube Download

# Generic formats supported by youtube-dl
genericFormats:
    best/bestvideo: Best
    bestvideo+bestaudio: Remux best video with best audio
    worst/worstvideo: Worst

# Enable debug mode.
debug: false

# True to enable audio conversion mode by default
defaultAudio: false

# False to disable convert seek functionality
convertSeek: true
*

```

**Please provide the URL of a video that causes the issue.**
https://www.tiktok.com/@lovesoreal/video/7064281466632408366
https://www.xvideos.com/video61039269/24151053/0/hungover_fuck_for_samantha_flair

## Describe your issue

Always get errors I have mentioned above I'm not sure how to update yt-dl any help would be appreciated
