### ISSUE TITLE
it takes long time to start download

### ISSUE THREAD

**Issue by gitxxfan** [Rudloff/alltube#404]
# New issue

## Your environment

Please answer these questions when reporting a new issue:

**What is your operating system (Windows, Linux, OSX, etc.)?**
Linux
**What is your web server (Apache, IIS, etc.)?**
nginx
**What version of AllTube are you using?**
3.0.2
**How did you install AllTube (with Git or with a release package)?**
release
**What version of PHP are you using?**
7.4
**What version of Python are you using?**
3.7
**What version of youtube-dl are you using?**
latest
**Do you get any PHP-related errors in your webserver's logs?**
no
**What is the content of your `config/config.yml` file?**

```yaml
---
# Path to your youtube-dl binary
youtubedl: vendor/ytdl-org/youtube-dl/youtube_dl/__main__.py

# Path to your python binary
python: /usr/bin/python3

# An array of parameters to pass to youtube-dl
params:
    - --no-warnings
    - --ignore-errors
    - --flat-playlist
    - --restrict-filenames
    - --no-playlist

# True to enable audio conversion
convert: false

# True to enable advanced conversion mode
convertAdvanced: false

# List of formats available in advanced conversion mode
convertAdvancedFormats: [mp3, avi, flv, wav]

# Path to your ffmpeg binary
ffmpeg: /usr/bin/ffmpeg
avconv: /usr/bin/ffmpeg

# ffmpeg logging level.
ffmpegVerbosity: error

# Path to the directory that contains the phantomjs binary.
phantomjsDir: /usr/bin/

# True to disable URL rewriting
uglyUrls: true

# True to stream videos through server
# Set to "ask" if you want to allow it but not enable by default.
stream: true

# True to enable remux mode (merge best audio and best video)
remux: false

# MP3 bitrate when converting (in kbit/s)
audioBitrate: 128

# App name
appName: Online Videos Download

# Generic formats supported by youtube-dl
genericFormats:
    best/bestvideo: Best
    bestvideo+bestaudio: Remux best video with best audio
    worst/worstvideo: Worst

# Enable debug mode.
debug: false

# True to enable audio conversion mode by default
defaultAudio: false

# False to disable convert seek functionality
convertSeek: true

```

**Please provide the URL of a video that causes the issue.**

## Describe your issue
after clicking download button on index page, it takes more than 15 seconds to redirect to info page, at info page , when I click the download button, it takes more than 20 seconds to start downloading,  what could be the reason for that please, my network has no issue, is there a way to improve that part?  please help me, Thank you very much.
