### ISSUE TITLE
mkv video losed playback information and cann't play normally

### ISSUE THREAD

**Issue by ershiyi21** [Rudloff/alltube#405]
# New issue

## Your environment

Please answer these questions when reporting a new issue:

**What is your operating system (Windows, Linux, OSX, etc.)?**
ubuntu20

**What is your web server (Apache, IIS, etc.)?**
LNMP

**What version of AllTube are you using?**
3.0.3

**How did you install AllTube (with Git or with a release package)?**
a release package

**What version of PHP are you using?**
74

**What version of Python are you using?**
3.8

**What version of youtube-dl are you using?**
[youtube-dl in3.0.3] or [yt-dlp 2022.03.08.1]

**Do you get any PHP-related errors in your webserver's logs?**
no

**What is the content of your `config/config.yml` file?**
```yaml
# Path to your youtube-dl binary
youtubedl: vendor/ytdl-org/yt-dlp/yt_dlp/__main__.py

# Path to your python binary
python: /usr/bin/python

# An array of parameters to pass to youtube-dl
params:
    - --no-warnings
    - --ignore-errors
    - --flat-playlist
    - --restrict-filenames
    - --no-playlist
    
# True to enable audio conversion
convert: true

# True to enable advanced conversion mode
convertAdvanced: true

# List of formats available in advanced conversion mode
convertAdvancedFormats: [mp3, avi, flv, wav]

# Path to your ffmpeg binary
ffmpeg: /usr/bin/ffmpeg

# ffmpeg logging level.
ffmpegVerbosity: error

# Path to the directory that contains the phantomjs binary.
phantomjsDir: /usr/bin/

# True to disable URL rewriting
uglyUrls: false

# True to stream videos through server
# Set to "ask" if you want to allow it but not enable by default.
stream: true

# True to enable remux mode (merge best audio and best video)
remux: true

# MP3 bitrate when converting (in kbit/s)
audioBitrate: 256

# App name
appName: AllTube Download

# Generic formats supported by youtube-dl
genericFormats:
    bestvideo+bestaudio: Remux best video with best audio
    best/bestvideo: Best
    worst/worstvideo: Worst

# Enable debug mode.
debug: false

# True to enable audio conversion mode by default
defaultAudio: false

# False to disable convert seek functionality
convertSeek: true
```

**Please provide the URL of a video that causes the issue.**
all youtube

## Describe your issue
When I download video from youtube in this way : "remux best video with best audio",then I get a mkv video [video-vp9 & audio-upos].However,this mkv video can not play normally in “network flow”：The time progress bar cannot be displayed normally, and the video progress cannot be dragged.I must download the whole mkv vedio file and play it in some player with fremg decoder such as potplayer and mxplayer[nplayer can not play normally even the whole mkv file is in local] ,if I want to play it with "right time progress bar".
![play-info](https://user-images.githubusercontent.com/68776500/158825843-8c788fbf-f3fd-4ed5-9c3a-77b49e15545d.png)
![wrong-info](https://user-images.githubusercontent.com/68776500/158826570-ce215bc7-d85c-4656-bc22-1a45a18c7932.png)
Both of them are in Internet video streaming

Comparing the information of the two, it is found that the mkv video mixed by the server lacks some playback information, and the mkv video that is re-distributed and packaged through mkvtoolnix can be played normally both locally and in the stream.

I tried youtube-dl and yt-dlp,and them showed the same problem.
