### ISSUE TITLE
always fail when downloading remux best video with best audio

### ISSUE THREAD

**Issue by gitxxfan** [Rudloff/alltube#409]
# New issue

## Your environment

Please answer these questions when reporting a new issue:

**What is your operating system (Windows, Linux, OSX, etc.)?**
linux
**What is your web server (Apache, IIS, etc.)?**
nginx
**What version of AllTube are you using?**
latest
**How did you install AllTube (with Git or with a release package)?**
release
**What version of PHP are you using?**
7.3
**What version of Python are you using?**
3.9
**What version of youtube-dl are you using?**
latest
**Do you get any PHP-related errors in your webserver's logs?**
no
**What is the content of your `config/config.yml` file?**

```yaml
---
# Path to your youtube-dl binary
# youtubedl: vendor/ytdl-org/youtube-dl/youtube_dl/__main__.py
youtubedl: vendor/yt-dlp/yt_dlp/__main__.py

# Path to your python binary
python: /usr/bin/python3

# An array of parameters to pass to youtube-dl
params:
    - --no-warnings
    - --ignore-errors
    - --flat-playlist
    - --restrict-filenames
    - --no-playlist

# True to enable audio conversion
convert: true

# True to enable advanced conversion mode
convertAdvanced: false

# List of formats available in advanced conversion mode
convertAdvancedFormats: [mp3, avi, flv, wav]

# Path to your ffmpeg binary
ffmpeg: /usr/bin/ffmpeg
avconv: /usr/bin/ffmpeg

# ffmpeg logging level.
ffmpegVerbosity: error

# Path to the directory that contains the phantomjs binary.
phantomjsDir: /usr/bin/

# True to disable URL rewriting
uglyUrls: false

# True to stream videos through server
# Set to "ask" if you want to allow it but not enable by default.
stream: false

# True to enable remux mode (merge best audio and best video)
remux: true

# MP3 bitrate when converting (in kbit/s)
audioBitrate: 128

# App name
appName: Tiktokdownloader

# Generic formats supported by youtube-dl
genericFormats:
    best/bestvideo: Best
    bestvideo+bestaudio: Remux best video with best audio
    worst/worstvideo: Worst

# Enable debug mode.
debug: false

# True to enable audio conversion mode by default
defaultAudio: false

# False to disable convert seek functionality
convertSeek: false

```

**Please provide the URL of a video that causes the issue.**
https://www.bilibili.com/video/BV1bA4y1D7qR?spm_id_from=333.1073.high_energy.content.click
## Describe your issue
I want to download videos from bilibili.com with alltube app, when I select the mp4 format, it can finish downloading but the video has no sound, when I select remux Mkv format,  it always fails due to network error reasons,  but when I download the video with yt-dlp app directly from my laptop,  it can finish downloading without any error.  Can anyone help check what caused the network error failures please? Thanks.
