### ISSUE TITLE
403 errror

### ISSUE THREAD

**Issue by bigfans233** [Rudloff/alltube#420]
### What is your operating system (Windows, Linux, OSX, etc.)?

Linux

### What is your web server (Apache, IIS, etc.)?

腾讯云

### What version of AllTube are you using?

lastest

### How did you install AllTube?

Git

### What version of PHP are you using?

7.3

### What version of Python are you using?

3.8

### What version of youtube-dl are you using?

yt-dpl

### Do you get any PHP-related errors in your webserver's logs?

```plain text
no
```

### What is the content of your "config/config.yml" file?

```yml
---
# Path to your youtube-dl binary
youtubedl: vendor/yt-dlp/yt_dlp/__main__.py

# Path to your python binary
python: /usr/bin/python3

# An array of parameters to pass to youtube-dl
params:
    - --no-warnings
    - --ignore-errors
    - --flat-playlist
    - --restrict-filenames
    - --no-playlist

# True to enable audio conversion
convert: true

# True to enable advanced conversion mode
convertAdvanced: true

# List of formats available in advanced conversion mode
convertAdvancedFormats: [mp3, avi, flv, wav]

# Path to your ffmpeg binary
ffmpeg: /usr/bin/ffmpeg

# ffmpeg logging level.
ffmpegVerbosity: error

# Path to the directory that contains the phantomjs binary.
phantomjsDir: /usr/bin/

# True to disable URL rewriting
uglyUrls: true

# True to stream videos through server
# Set to "ask" if you want to allow it but not enable by default.
stream: ask

# True to enable remux mode (merge best audio and best video)
remux: True

# MP3 bitrate when converting (in kbit/s)
audioBitrate: 128

# App name
appName: AllTube Download

# Generic formats supported by youtube-dl
genericFormats:
    best/bestvideo: Best
    bestvideo+bestaudio: Remux best video with best audio
    worst/worstvideo: Worst

# Enable debug mode.
debug: false

# True to enable audio conversion mode by default
defaultAudio: false

# False to disable convert seek functionality
convertSeek: true
```

### Please provide the URL of a video that causes the issue.

https://www.bilibili.com/video/BV1aG411s76j

### Describe your issue

Client error: `GET https://upos-sz-mirrorcosb.bilivideo.com/upgcxcode/82/25/754382582/754382582_nb3-1-30232.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1656308675&gen=playurlv2&os=cosbbv&oi=2094952164&trid=b1107f4a644f40f69282d954d9ea5822u&mid=0&platform=pc&upsig=c9ae3b5d9ee58501a905d478c07aad82&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&bvc=vod&nettype=0&orderid=2,3&agrr=1&bw=16646&logo=40000000` resulted in a `403 Forbidden` response

when i Stream the video through the server 
it reture 403
i think it need header
![捕获](https://user-images.githubusercontent.com/78126439/175856398-a7911365-bc6b-4793-bc90-a64cb6935658.PNG)
