### ISSUE TITLE
network error

### ISSUE THREAD

**Issue by gitxxfan** [Rudloff/alltube#423]
### What is your operating system (Windows, Linux, OSX, etc.)?

linux

### What is your web server (Apache, IIS, etc.)?

nginx

### What version of AllTube are you using?

3.0.3

### How did you install AllTube?

Git

### What version of PHP are you using?

7.3

### What version of Python are you using?

3.10

### What version of youtube-dl are you using?

latest

### Do you get any PHP-related errors in your webserver's logs?

```plain text
no
```

### What is the content of your "config/config.yml" file?

```yml
---
# Path to your youtube-dl binary
# youtubedl: vendor/ytdl-org/youtube-dl/youtube_dl/__main__.py
youtubedl: vendor/yt-dlp/yt_dlp/__main__.py

# Path to your python binary
python: /usr/bin/python3

# An array of parameters to pass to youtube-dl
params:
    - --no-warnings
    - --ignore-errors
    - --flat-playlist
    - --restrict-filenames
    - --no-playlist

# True to enable audio conversion
convert: false

# True to enable advanced conversion mode
convertAdvanced: false

# List of formats available in advanced conversion mode
convertAdvancedFormats: [mp3, avi, flv, wav]

# Path to your ffmpeg binary
ffmpeg: /usr/bin/ffmpeg
avconv: /usr/bin/ffmpeg

# ffmpeg logging level.
ffmpegVerbosity: error

# Path to the directory that contains the phantomjs binary.
phantomjsDir: /usr/bin/

# True to disable URL rewriting
uglyUrls: false

# True to stream videos through server
# Set to "ask" if you want to allow it but not enable by default.
stream: true

# True to enable remux mode (merge best audio and best video)
remux: false

# MP3 bitrate when converting (in kbit/s)
audioBitrate: 128

# App name
appName:Videos Download

# Generic formats supported by youtube-dl
genericFormats:
    best/bestvideo: Best
    bestvideo+bestaudio: Remux best video with best audio
    worst/worstvideo: Worst

# Enable debug mode.
debug: false

# True to enable audio conversion mode by default
defaultAudio: false

# False to disable convert seek functionality
convertSeek: true
```

### Please provide the URL of a video that causes the issue.

https://91porn.com/view_video.php?viewkey=96278e11c29d2f4e086c&c=t&viewtype=&category=

### Describe your issue

![cRn94xe4UL](https://user-images.githubusercontent.com/98593497/187911102-3b382986-f16b-4984-a549-9398165c2388.jpg)
as the capture shows,   network error always happen when I  trying to download a longer video,    whats wrong with that please ?   i can download the video successfully when using yt-dlp from my local computer, even the speed is not good,  but always fails when trying to download through alltube app, please help  ,Thanks.
